### ISSUE TITLE
Hardcoded Path

### ISSUE THREAD

**Issue by constructdian** [ktreese/nssm#1]
Hiya, thanks for this module - it's come in very useful.

The hardcoded path to NSSM exe is problematic, as not everyone will have it installed in the default location (and the version is hardcoded into the path, so additional issues for people not running latest). I had to remove this to get it to work (I have path variables set globally and my nssm is installed by choco in a non default location)

Probably worth a fix.

**Comment by ktreese** [comment]
@constructdian I see what you mean.  I'll work to refactor so that it can be specified.  In the meantime, I've had issues in the past getting NSSM to install via choco (see https://chocolatey.org/packages/NSSM#comment-2768333292 as reference).  Seems like you didn't have any trouble?

**Comment by ktreese** [comment]
Addressed in #2 

@constructdian
